// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: balance.sql

package db

import (
	"context"
)

const getUserBalance = `-- name: GetUserBalance :one
SELECT 
    u.balance + 
    COALESCE(SUM(CASE WHEN t.type_transaction = 'ACCRUAL' THEN t.amount ELSE 0 END), 0) - 
    COALESCE(SUM(CASE WHEN t.type_transaction = 'WITHDRAWAL' THEN t.amount ELSE 0 END), 0) AS current,
    CAST(COALESCE(SUM(CASE WHEN t.type_transaction = 'WITHDRAWAL' THEN t.amount ELSE 0 END), 0) AS FLOAT) AS withdrawn
FROM users u
LEFT JOIN Transactions t ON u.id = t.user_id
WHERE u.id = $1
GROUP BY u.id
`

type GetUserBalanceRow struct {
	Current   int32   `db:"current" json:"current"`
	Withdrawn float64 `db:"withdrawn" json:"withdrawn"`
}

func (q *Queries) GetUserBalance(ctx context.Context, id int32) (GetUserBalanceRow, error) {
	row := q.db.QueryRowContext(ctx, getUserBalance, id)
	var i GetUserBalanceRow
	err := row.Scan(&i.Current, &i.Withdrawn)
	return i, err
}
