// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"
)

type Order struct {
	ID        int32     `db:"id" json:"id"`
	UserID    int32     `db:"user_id" json:"user_id"`
	Status    string    `db:"status" json:"status"`
	Accrual   float64   `db:"accrual" json:"accrual"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type Transaction struct {
	ID              int32     `db:"id" json:"id"`
	UserID          int32     `db:"user_id" json:"user_id"`
	OrderID         int32     `db:"order_id" json:"order_id"`
	TypeTransaction string    `db:"type_transaction" json:"type_transaction"`
	Amount          float64   `db:"amount" json:"amount"`
	CreatedAt       time.Time `db:"created_at" json:"created_at"`
}

type User struct {
	ID        int32     `db:"id" json:"id"`
	Login     string    `db:"login" json:"login"`
	Password  string    `db:"password" json:"password"`
	Role      string    `db:"role" json:"role"`
	Balance   float64   `db:"balance" json:"balance"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}
