// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: transactions.sql

package db

import (
	"context"
)

const createAccrualTransaction = `-- name: CreateAccrualTransaction :exec
INSERT INTO Transactions(user_id, order_id, type_transaction, amount)
VALUES ($1, $2, 'ACCRUAL', $3)
`

type CreateAccrualTransactionParams struct {
	UserID  int32   `db:"user_id" json:"user_id"`
	OrderID int32   `db:"order_id" json:"order_id"`
	Amount  float64 `db:"amount" json:"amount"`
}

func (q *Queries) CreateAccrualTransaction(ctx context.Context, arg CreateAccrualTransactionParams) error {
	_, err := q.db.ExecContext(ctx, createAccrualTransaction, arg.UserID, arg.OrderID, arg.Amount)
	return err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO Transactions (user_id, order_id, type_transaction, amount) 
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, order_id, type_transaction, amount, created_at
`

type CreateTransactionParams struct {
	UserID          int32   `db:"user_id" json:"user_id"`
	OrderID         int32   `db:"order_id" json:"order_id"`
	TypeTransaction string  `db:"type_transaction" json:"type_transaction"`
	Amount          float64 `db:"amount" json:"amount"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.UserID,
		arg.OrderID,
		arg.TypeTransaction,
		arg.Amount,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrderID,
		&i.TypeTransaction,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const createWithdrawalTransaction = `-- name: CreateWithdrawalTransaction :exec
INSERT INTO Transactions(user_id, order_id, type_transaction, amount)
VALUES ($1, $2, 'WITHDRAWAL', $3)
`

type CreateWithdrawalTransactionParams struct {
	UserID  int32   `db:"user_id" json:"user_id"`
	OrderID int32   `db:"order_id" json:"order_id"`
	Amount  float64 `db:"amount" json:"amount"`
}

func (q *Queries) CreateWithdrawalTransaction(ctx context.Context, arg CreateWithdrawalTransactionParams) error {
	_, err := q.db.ExecContext(ctx, createWithdrawalTransaction, arg.UserID, arg.OrderID, arg.Amount)
	return err
}
